/**
 * lib/exams.ts — Single source of truth for all exam content.
 *
 * To add a new exam:
 *   1. Add a new entry to EXAM_CONFIGS below with a unique slug key.
 *   2. Fill in name, subtitle, description, durationSeconds, and questions[].
 *   3. Done — the route /{slug}, /{slug}/instructions, /{slug}/exam, /{slug}/result
 *      are all auto-generated by Next.js via generateStaticParams.
 */
import type { ExamConfig, Question } from "./types";

// Re-export so consumers can import ExamConfig from one place
export type { ExamConfig } from "./types";

// ─── Question banks ───────────────────────────────────────────────────────────

const ugdbeQuestions: Question[] = [
  // ── SECTION 1: DECISION MAKING ──────────────────────────────────────────
  {
    id: 1,
    text: "A brand gets high traffic but low sales. What should they check first?",
    options: ["Ad budget", "Product price vs perceived value", "Office costs", "Hiring"],
    correctAnswer: "Product price vs perceived value",
    marks: 4,
  },
  {
    id: 2,
    text: "A product has great reviews but poor sales. What is most likely the issue?",
    options: ["Product quality", "Distribution or visibility", "Customer satisfaction", "Manufacturing"],
    correctAnswer: "Distribution or visibility",
    marks: 4,
  },
  {
    id: 3,
    text: "A founder keeps changing ideas every month. What is the real problem?",
    options: ["The market is bad", "Lack of patience & conviction", "Team size", "Competition"],
    correctAnswer: "Lack of patience & conviction",
    marks: 4,
  },
  {
    id: 4,
    text: "Two businesses — Business A: ₹10L revenue, ₹1L profit | Business B: ₹5L revenue, ₹2L profit. Which business is performing better?",
    options: ["Business A", "Business B", "Both the same", "Cannot say"],
    correctAnswer: "Business B",
    marks: 4,
  },
  // ── SECTION 2: BUSINESS INSTINCT ────────────────────────────────────────
  {
    id: 5,
    text: "A startup is growing fast but losing money on every sale. What is the risk?",
    options: ["Faster success", "Unsustainable growth", "Better branding", "More users"],
    correctAnswer: "Unsustainable growth",
    marks: 4,
  },
  {
    id: 6,
    text: "You have ₹10,000. What is the best way to test a business idea?",
    options: ["Build a full product", "Run small experiments", "Spend on logo", "Hire team"],
    correctAnswer: "Run small experiments",
    marks: 4,
  },
  {
    id: 7,
    text: "Which is the strongest signal of product success?",
    options: ["Likes", "Repeat customers", "Website visits", "Followers"],
    correctAnswer: "Repeat customers",
    marks: 4,
  },
  // ── SECTION 3: NUMBERS THAT MATTER ──────────────────────────────────────
  {
    id: 8,
    text: "You sell at ₹1000, the cost is ₹900. What is the issue?",
    options: ["High revenue", "Low margin", "High demand", "Branding"],
    correctAnswer: "Low margin",
    marks: 4,
  },
  {
    id: 9,
    text: "A business doubles revenue but triples costs. What is the result?",
    options: ["Profit increases", "Profit decreases", "No change", "Break-even"],
    correctAnswer: "Profit decreases",
    marks: 4,
  },
  {
    id: 10,
    text: "You acquire 100 customers, but only 10 stay. What should you fix?",
    options: ["Acquisition", "Retention", "Branding", "Hiring"],
    correctAnswer: "Retention",
    marks: 4,
  },
  // ── SECTION 4: DIGITAL THINKING ─────────────────────────────────────────
  {
    id: 11,
    text: "Why do most ads fail?",
    options: ["Low budget", "Wrong message or audience", "Platform issue", "Timing"],
    correctAnswer: "Wrong message or audience",
    marks: 4,
  },
  {
    id: 12,
    text: "Why do some creators grow faster than others?",
    options: ["Luck", "Consistency + positioning", "Equipment", "Ads"],
    correctAnswer: "Consistency + positioning",
    marks: 4,
  },
  {
    id: 13,
    text: "A post gets views but no engagement. Why?",
    options: ["Algorithm", "Weak content", "Timing", "Hashtags"],
    correctAnswer: "Weak content",
    marks: 4,
  },
  // ── SECTION 5: BUILDER MINDSET ───────────────────────────────────────────
  {
    id: 14,
    text: "A businessman waits for the perfect idea. What is the issue?",
    options: ["Intelligence", "Overthinking", "Dissatisfaction", "Market"],
    correctAnswer: "Overthinking",
    marks: 4,
  },
  {
    id: 15,
    text: "What separates builders from talkers?",
    options: ["Knowledge", "Action", "Degree", "Experience"],
    correctAnswer: "Action",
    marks: 4,
  },
  {
    id: 16,
    text: "What matters most over 3–5 years?",
    options: ["Talent", "Consistency", "Luck", "Degree"],
    correctAnswer: "Consistency",
    marks: 4,
  },
  // ── OPEN-ENDED QUESTIONS ─────────────────────────────────────────────────
  {
    id: 17,
    text: "If you had to start a business in 2026, what would the business be about? (Answer in brief)",
    options: [],
    correctAnswer: "",
    marks: 0,
    type: "open",
  },
  {
    id: 18,
    text: "Which are some profit-making startups that you are aware of? How are they different from the others?",
    options: [],
    correctAnswer: "",
    marks: 0,
    type: "open",
  },
  {
    id: 19,
    text: "Name 2 content creators who run businesses and what their businesses are about.",
    options: [],
    correctAnswer: "",
    marks: 0,
    type: "open",
  },
  {
    id: 20,
    text: "If a new ice cream brand called Loco had to make its mark, which would they prefer: online sales or offline sales? And why?",
    options: [],
    correctAnswer: "",
    marks: 0,
    type: "open",
  },
];

const techScholarshipQuestions: Question[] = [
  {
    id: 1,
    text: "What does HTTP stand for?",
    options: [
      "HyperText Transfer Protocol",
      "High Transfer Text Protocol",
      "HyperText Transmission Process",
      "Hosted Text Transport Protocol",
    ],
    correctAnswer: "HyperText Transfer Protocol",
    marks: 2,
  },
  {
    id: 2,
    text: "Which data structure uses FIFO ordering?",
    options: ["Stack", "Tree", "Queue", "Heap"],
    correctAnswer: "Queue",
    marks: 4,
  },
  {
    id: 3,
    text: "What is the time complexity of binary search on a sorted array?",
    options: ["O(n)", "O(n²)", "O(1)", "O(log n)"],
    correctAnswer: "O(log n)",
    marks: 6,
  },
  {
    id: 4,
    text: "Which programming paradigm treats computation as the evaluation of mathematical functions?",
    options: ["Object-Oriented", "Procedural", "Functional", "Imperative"],
    correctAnswer: "Functional",
    marks: 4,
  },
  {
    id: 5,
    text: "In networking, what does DNS resolve?",
    options: [
      "IP addresses to MAC addresses",
      "Domain names to IP addresses",
      "HTTP requests to HTTPS",
      "Ports to protocols",
    ],
    correctAnswer: "Domain names to IP addresses",
    marks: 4,
  },
  {
    id: 6,
    text: "Which SQL clause is used to filter grouped results?",
    options: ["WHERE", "FILTER", "HAVING", "GROUP BY"],
    correctAnswer: "HAVING",
    marks: 6,
  },
  {
    id: 7,
    text: "What does API stand for?",
    options: [
      "Application Protocol Interface",
      "Application Programming Interface",
      "Automated Process Integration",
      "Advanced Program Interaction",
    ],
    correctAnswer: "Application Programming Interface",
    marks: 2,
  },
  {
    id: 8,
    text: "Which version control command creates a new branch and switches to it?",
    options: ["git merge", "git branch", "git checkout -b", "git init"],
    correctAnswer: "git checkout -b",
    marks: 4,
  },
  {
    id: 9,
    text: "What is 'Big O notation' used to describe?",
    options: [
      "Code readability score",
      "Algorithm efficiency relative to input size",
      "Memory usage in bytes",
      "Number of lines of code",
    ],
    correctAnswer: "Algorithm efficiency relative to input size",
    marks: 4,
  },
  {
    id: 10,
    text: "Which HTTP status code indicates a resource was not found?",
    options: ["200", "301", "403", "404"],
    correctAnswer: "404",
    marks: 4,
  },
  {
    id: 11,
    text: "Which of the following is NOT a JavaScript data type?",
    options: ["String", "Boolean", "Float", "Symbol"],
    correctAnswer: "Float",
    marks: 4,
  },
  {
    id: 12,
    text: "What does 'SSL/TLS' provide in web communication?",
    options: [
      "Faster page load speeds",
      "Encrypted and secure data transmission",
      "Server-side rendering",
      "Caching of static assets",
    ],
    correctAnswer: "Encrypted and secure data transmission",
    marks: 4,
  },
  {
    id: 13,
    text: "In object-oriented programming, 'encapsulation' means?",
    options: [
      "Inheriting properties from a parent class",
      "Bundling data and methods that operate on it within a single unit",
      "Overriding a method in a subclass",
      "Creating multiple instances of a class",
    ],
    correctAnswer: "Bundling data and methods that operate on it within a single unit",
    marks: 6,
  },
  {
    id: 14,
    text: "What does 'CRUD' stand for in database operations?",
    options: [
      "Create, Read, Update, Delete",
      "Connect, Retrieve, Upload, Deploy",
      "Cache, Render, Update, Delete",
      "Compile, Run, Upload, Debug",
    ],
    correctAnswer: "Create, Read, Update, Delete",
    marks: 4,
  },
  {
    id: 15,
    text: "Which sorting algorithm has the best average-case time complexity?",
    options: ["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"],
    correctAnswer: "Merge Sort",
    marks: 6,
  },
];

const scienceScholarshipQuestions: Question[] = [
  {
    id: 1,
    text: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: "Au",
    marks: 2,
  },
  {
    id: 2,
    text: "Newton's second law of motion states that Force equals?",
    options: ["mass × velocity", "mass × acceleration", "energy / time", "momentum / distance"],
    correctAnswer: "mass × acceleration",
    marks: 4,
  },
  {
    id: 3,
    text: "Which organelle is known as the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Golgi apparatus", "Mitochondria"],
    correctAnswer: "Mitochondria",
    marks: 4,
  },
  {
    id: 4,
    text: "What is the atomic number of carbon?",
    options: ["4", "6", "8", "12"],
    correctAnswer: "6",
    marks: 4,
  },
  {
    id: 5,
    text: "The process by which plants make food using sunlight is called?",
    options: ["Respiration", "Fermentation", "Photosynthesis", "Transpiration"],
    correctAnswer: "Photosynthesis",
    marks: 2,
  },
  {
    id: 6,
    text: "What is the speed of light in a vacuum approximately?",
    options: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10¹² m/s"],
    correctAnswer: "3 × 10⁸ m/s",
    marks: 6,
  },
  {
    id: 7,
    text: "Which gas makes up the largest percentage of Earth's atmosphere?",
    options: ["Oxygen", "Carbon dioxide", "Argon", "Nitrogen"],
    correctAnswer: "Nitrogen",
    marks: 4,
  },
  {
    id: 8,
    text: "What type of bond involves the sharing of electron pairs between atoms?",
    options: ["Ionic bond", "Metallic bond", "Covalent bond", "Hydrogen bond"],
    correctAnswer: "Covalent bond",
    marks: 6,
  },
  {
    id: 9,
    text: "Which scientist developed the theory of general relativity?",
    options: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"],
    correctAnswer: "Albert Einstein",
    marks: 4,
  },
  {
    id: 10,
    text: "The SI unit of electric current is?",
    options: ["Volt", "Watt", "Ampere", "Ohm"],
    correctAnswer: "Ampere",
    marks: 4,
  },
  {
    id: 11,
    text: "What is the process of nuclear fusion?",
    options: [
      "Splitting a heavy nucleus into smaller ones",
      "Combining light nuclei to form a heavier nucleus releasing energy",
      "Converting matter directly into electricity",
      "Radioactive decay of unstable isotopes",
    ],
    correctAnswer: "Combining light nuclei to form a heavier nucleus releasing energy",
    marks: 6,
  },
  {
    id: 12,
    text: "Which law states that the pressure of a gas is inversely proportional to its volume at constant temperature?",
    options: ["Charles's Law", "Avogadro's Law", "Boyle's Law", "Gay-Lussac's Law"],
    correctAnswer: "Boyle's Law",
    marks: 4,
  },
  {
    id: 13,
    text: "What is the primary function of white blood cells?",
    options: [
      "Carrying oxygen throughout the body",
      "Clotting blood at wound sites",
      "Defending the body against infections",
      "Transporting nutrients from the digestive system",
    ],
    correctAnswer: "Defending the body against infections",
    marks: 4,
  },
  {
    id: 14,
    text: "In the periodic table, elements in the same column share?",
    options: [
      "The same atomic mass",
      "The same number of protons",
      "Similar chemical properties",
      "The same electron configuration",
    ],
    correctAnswer: "Similar chemical properties",
    marks: 4,
  },
  {
    id: 15,
    text: "What type of wave does NOT require a medium to travel?",
    options: ["Sound wave", "Water wave", "Electromagnetic wave", "Seismic wave"],
    correctAnswer: "Electromagnetic wave",
    marks: 6,
  },
];

const managementScholarshipQuestions: Question[] = [
  {
    id: 1,
    text: "What does GDP stand for?",
    options: [
      "Gross Domestic Product",
      "General Development Plan",
      "Global Distribution Protocol",
      "Growth & Development Program",
    ],
    correctAnswer: "Gross Domestic Product",
    marks: 2,
  },
  {
    id: 2,
    text: "Which leadership style involves maximum employee participation in decision-making?",
    options: ["Autocratic", "Democratic", "Laissez-faire", "Transactional"],
    correctAnswer: "Democratic",
    marks: 4,
  },
  {
    id: 3,
    text: "Maslow's Hierarchy of Needs places which need at the top?",
    options: ["Safety", "Esteem", "Social belonging", "Self-actualization"],
    correctAnswer: "Self-actualization",
    marks: 4,
  },
  {
    id: 4,
    text: "What is the primary goal of supply chain management?",
    options: [
      "Maximizing warehouse space",
      "Reducing the number of suppliers",
      "Delivering the right product to the right place at the right time efficiently",
      "Increasing employee headcount",
    ],
    correctAnswer: "Delivering the right product to the right place at the right time efficiently",
    marks: 4,
  },
  {
    id: 5,
    text: "Porter's Five Forces does NOT include?",
    options: [
      "Threat of new entrants",
      "Bargaining power of suppliers",
      "Employee satisfaction",
      "Competitive rivalry",
    ],
    correctAnswer: "Employee satisfaction",
    marks: 6,
  },
  {
    id: 6,
    text: "A company's balance sheet shows?",
    options: [
      "Revenue and expenses over a period",
      "Cash inflows and outflows",
      "Assets, liabilities, and equity at a point in time",
      "Market share data",
    ],
    correctAnswer: "Assets, liabilities, and equity at a point in time",
    marks: 6,
  },
  {
    id: 7,
    text: "What does B2B stand for in commerce?",
    options: ["Brand to Buyer", "Business to Business", "Budget to Budget", "Back to Basics"],
    correctAnswer: "Business to Business",
    marks: 2,
  },
  {
    id: 8,
    text: "Which project management methodology uses sprints?",
    options: ["Waterfall", "PRINCE2", "Six Sigma", "Agile/Scrum"],
    correctAnswer: "Agile/Scrum",
    marks: 4,
  },
  {
    id: 9,
    text: "Break-even point is where?",
    options: [
      "Total revenue equals total costs",
      "Profit is maximized",
      "Fixed costs equal variable costs",
      "Sales equal zero",
    ],
    correctAnswer: "Total revenue equals total costs",
    marks: 4,
  },
  {
    id: 10,
    text: "What is 'market segmentation'?",
    options: [
      "Dividing the market into distinct groups of buyers with different needs",
      "Setting different prices for different products",
      "Splitting a company into subsidiaries",
      "Measuring total market size",
    ],
    correctAnswer: "Dividing the market into distinct groups of buyers with different needs",
    marks: 4,
  },
  {
    id: 11,
    text: "What is 'economies of scale'?",
    options: [
      "The study of national economic output",
      "Cost advantages gained by increasing production volume",
      "A pricing strategy for luxury goods",
      "The process of outsourcing to reduce costs",
    ],
    correctAnswer: "Cost advantages gained by increasing production volume",
    marks: 4,
  },
  {
    id: 12,
    text: "Which financial statement shows a company's revenues and expenses over a period?",
    options: ["Balance Sheet", "Cash Flow Statement", "Income Statement", "Equity Report"],
    correctAnswer: "Income Statement",
    marks: 4,
  },
  {
    id: 13,
    text: "'Diversification' as a business strategy means?",
    options: [
      "Reducing the product line to focus on one item",
      "Entering new markets or developing new products to spread risk",
      "Increasing the price of existing products",
      "Acquiring a direct competitor",
    ],
    correctAnswer: "Entering new markets or developing new products to spread risk",
    marks: 6,
  },
  {
    id: 14,
    text: "What does 'ROI' stand for?",
    options: ["Rate of Inflation", "Return on Investment", "Revenue over Income", "Risk of Insolvency"],
    correctAnswer: "Return on Investment",
    marks: 2,
  },
  {
    id: 15,
    text: "The 'Boston Matrix' is used to?",
    options: [
      "Analyze employee performance",
      "Classify products based on market growth and market share",
      "Map supply chain logistics",
      "Plan marketing campaigns",
    ],
    correctAnswer: "Classify products based on market growth and market share",
    marks: 6,
  },
];

// ─── Exam registry ────────────────────────────────────────────────────────────

export const EXAM_CONFIGS: Record<string, ExamConfig> = {
  ugdbe: {
    slug: "ugdbe",
    name: "UGDBE 2026",
    subtitle: "Under Graduate Design & Business Exam",
    description:
      "A proctored scholarship exam covering decision making, business instinct, numbers, digital thinking, and builder mindset.",
    durationSeconds: 2700,
    questions: ugdbeQuestions,
  },
  "tech-scholarship": {
    slug: "tech-scholarship",
    name: "Tech Scholarship 2026",
    subtitle: "Technology & Computer Science Exam",
    description:
      "A proctored scholarship exam covering programming fundamentals, networking, and data structures.",
    durationSeconds: 300,
    questions: techScholarshipQuestions,
  },
  "science-scholarship": {
    slug: "science-scholarship",
    name: "Science Scholarship 2026",
    subtitle: "Physics, Chemistry & Biology Exam",
    description:
      "A proctored scholarship exam covering core concepts in physics, chemistry, and biology.",
    durationSeconds: 300,
    questions: scienceScholarshipQuestions,
  },
  "management-scholarship": {
    slug: "management-scholarship",
    name: "Management Scholarship 2026",
    subtitle: "Business Management & Strategy Exam",
    description:
      "A proctored scholarship exam covering management principles, strategy, and business economics.",
    durationSeconds: 300,
    questions: managementScholarshipQuestions,
  },
};

export function getExamConfig(slug: string): ExamConfig | null {
  return EXAM_CONFIGS[slug] ?? null;
}

export function getAllExamSlugs(): string[] {
  return Object.keys(EXAM_CONFIGS);
}

export function getTotalMarks(config: ExamConfig): number {
  return config.questions.reduce((sum, q) => sum + q.marks, 0);
}
